title: White Water Writers
url: http://equalitytime.github.io
baseurl: 

page_gen-dirs: true
kramdown:
 parse_block_html: true

plugins: 
  - jekyll-sitemap


url: "https://www.whitewaterwriters.com/"
